<?php
declare(strict_types=1);

namespace app\modules\v2\operateDept\domain\dto;

use yii\base\Model;

/**
 * Class DesignCenterDto
 * @property int $beginTime
 * @property int $endTime
 * @package app\modules\v2\operateDept\domain\dto
 */
class DesignCenterDto extends Model
{
    public const SEARCH = 'search';

    //注意：编辑时前端需要传 scenario 字段，值为edit
    public const EDIT = 'edit';
    public const READ = 'read';
    public const AUDIT = 'audit';

    public $scenario;

    /** @var int */
    public $id;
    /** @var string */
    public $version;
    /** @var string */
    public $name;
    /** @var string */
    public $stylist;
    /** @var string */
    public $picture_address;
    /** @var int */
    public $upload_time;
    /** @var int */
    public $audit_status;
    /** @var string */
    public $audit_opinion;
    /** @var string */
    public $auditor;
    /** @var int */
    public $beginTime;
    /** @var int */
    public $endTime;

    public function rules(): array
    {
        return [
            [['name', 'stylist','audit_status','upload_time','beginTime','endTime'], 'string', 'on' => self::SEARCH],
            [['version', 'name', 'stylist', 'picture_address'], 'string', 'on' => self::EDIT],
            ['id', 'integer', 'on' => self::EDIT],
            ['id', 'integer', 'on' => self::READ],
            [['id', 'audit_status'], 'integer', 'on' => self::AUDIT],
            [['audit_opinion','auditor'], 'string', 'on' => self::AUDIT],
            ['scenario', 'in', 'range' => [self::SEARCH,self::READ,self::AUDIT], 'message' => '场景值错误'],
        ];
    }




    public function attributeLabels(): array
    {
        return [
            //-----------搜索--------------
            'upload_time' => '上传时间',
            'name' => '名称',
            'stylist' => '设计师',
            'audit_status' => '审核状态',
            //-----------编辑---------------
            'version' => '版本',
            'picture_address' => '图片地址',
            //-----------审核-----------
            'audit_opinion' => '审核意见',
            'auditor' => '审核人',
        ];
    }


    public function fields(): array
    {
        switch ($this->getScenario()) {
            case self::SEARCH :
                return parent::fields();
            case self::EDIT :
                return [
                    'version',
                    'name',
                    'stylist',
                    'picture_address',
                ];
            case self::AUDIT :
                return [
                    'audit_status',
                    'audit_opinion',
                    'auditor',
                ];
            default:
                return parent::fields();
        }
    }


    public function setScenario($value)
    {
        parent::setScenario($value); // TODO: Change the autogenerated stub
        return $this;
    }


    /**
     * @return int
     */
    public function getBeginTime(): ?int
    {
        return $this->beginTime;
    }

    /**
     * @param string $beginTime
     */
    public function setBeginTime(string $beginTime): void
    {
        $this->beginTime = strtotime($beginTime);
    }

    /**
     * @return int
     */
    public function getEndTime(): ?int
    {
        return $this->endTime;
    }

    /**
     * @param string $endTime
     */
    public function setEndTime(string $endTime): void
    {
        $this->endTime = strtotime($endTime);
    }


    /**
     * @return int
     */
    public function getUploadTime(): int
    {
        return $this->upload_time;
    }

    /**
     * @param int $upload_time
     */
    public function setUploadTime(int $upload_time): void
    {
        $this->upload_time = strtotime($upload_time);
    }


}