<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: F
 * Date: 2019/10/17
 * Time: 19:59
 */

namespace app\modules\v2\advertDept\domain\dto;


use yii\base\Model;

class ProductLibraryDto extends Model
{
    public const SEARCH = 'search';
    public const DELETE = 'delete';
    public const READ = 'read';

    public $scenario;

    /** @var int */
    public $id;
    /** @var string */
    public $product_name;
    /** @var string */
    public $commission_rate;
    /** @var string */
    public $founder;
    /** @var int */
    public $create_at;
    /** @var int */
    public $beginTime;
    /** @var int */
    public $endTime;
    /** @var int */
    public $page;
    /** @var int */
    public $perPage;

    public function rules():array
    {
        return [
            [['id','page','perPage'], 'integer'],
            [['beginTime', 'endTime', 'product_name'], 'string', 'on' => self::SEARCH],
            ['id', 'integer', 'on' => self::READ],
            ['id', 'required', 'on' => self::READ],
            ['id', 'integer', 'on' => self::DELETE],
            ['id', 'required', 'on' => self::DELETE],
            ['scenario', 'in', 'range' => [self::SEARCH, self::DELETE, self::READ], 'message' => '场景值错误'],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            //-----------搜索--------------
            'endTime' => '开始时间',
            'beginTime' => '结束时间',
            'product_name' => '产品名称',
            //-----------删除--------------
            //-----------读取--------------
            'id' => 'ID',
        ];
    }

    public function fields(): array
    {
        switch ($this->getScenario()) {
            case self::SEARCH :
                return parent::fields();
            case self::READ :
                return ['id'];
            case self::DELETE :
                return ['id'];
            default:
                return parent::fields();
        }
    }

    public function setScenario($value)
    {
        parent::setScenario($value); // TODO: Change the autogenerated stub
        return $this;
    }
}