<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: F
 * Date: 2019/10/17
 * Time: 20:18
 */

namespace app\modules\v2\advertDept\domain\dto;


use yii\base\Model;

class ProductLibraryForm extends Model
{
    public const UPDATE = 'update';
    public const CREATE = 'create';

    /** @var int */
    public $id;
    /** @var string */
    public $product_name;
    /** @var string */
    public $commission_rate;

    public function rules():array
    {
        return [
            ['id', 'integer', 'on' => self::UPDATE],
            ['id', 'required', 'on' => self::UPDATE],
            [['product_name','commission_rate'], 'string'],
            [['product_name','commission_rate'], 'required'],
            ['commission_rate', 'requiredByASpecial'],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            //-----------创建--------------
            'product_name' => '产品名称',
            'commission_rate' => '抽佣率（%）',
            //-----------更新--------------
            'id' => 'ID',
        ];
    }

    public function setScenario($value)
    {
        parent::setScenario($value); // TODO: Change the autogenerated stub
        return $this;
    }

    public function requiredByASpecial($attribute): bool
    {
        $data = ['commission_rate' => '抽佣率（%）'];
        $relus = "/^[0-9]*(\.?(\d{1,2}))$/";    //验证正整数或者小数点后一道两位数的小数
        if(preg_match($relus, (string)$this->getAttributes([$attribute])[$attribute]) !== 1){
            $this->addError($attribute, $data[$attribute] . '的值只能是正整数或者小数点后一道两位数的小数');
            return false;
        }
        return true;
    }
}